### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by lzyvi3t** [Industrial/idTweaks#1]
I love the features of the addon but I still enjoy using the blizz action bar.. is there a way you can make it toggleable incase there are users who want to use it still?

**Comment by Industrial** [comment]
Hi!

Thanks for your ticket!

It's certainly supposed to work that way. I'm going to fix that right away :-)

**Comment by Industrial** [comment]
Done! Fixed with **v1.13.2-1.10.0**

https://wowinterface.com/downloads/fileinfo.php?id=23978#info
https://www.curseforge.com/wow/addons/idtweaks

**Comment by Industrial** [comment]
@lzyvi3t Was your issue fixed?
