### ISSUE TITLE
Petbar is impacted even when Actionbar tweaks are disabled

### ISSUE THREAD

**Issue by FloppyBob** [Industrial/idTweaks#2]
Hi great addon I just have o ne small problem when you target somerhing the Petbar is impacted with the actionbar tweaks even when Actionbar tweaks are disabled. I hope you can fix this 

Thanks

**Comment by Industrial** [comment]
Hi! I'll look at this now :-)

**Comment by Industrial** [comment]
The pet bar is a nasty piece of code in classic, I can't seem to fix it properly.

I band-aided it by reloading the UI on Enable/Disable. For now that's good enough. At least it works correctly now, but I'm keeping the ticket open.
