### ISSUE TITLE
Error on Classic.

### ISSUE THREAD

**Issue by Havenloft** [Industrial/idTweaks#3]
I disable the Action Bars for this addon. I use Dominos.
Error on Classic:

1x idTweaks\src\modules\ActionBars.lua:198: attempt to index field 'bar1' (a nil value)
idTweaks\src\modules\ActionBars.lua:198: in function `disableActionBars'
idTweaks\src\modules\ActionBars.lua:181: in function `disable'
idTweaks\src\modules\ActionBars.lua:162: in function `check'
idTweaks\src\modules\ActionBars.lua:147: in function <idTweaks\src\modules\ActionBars.lua:142>
[C]: ?
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:540: in function `EnableAddon'
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:693: in function <FrameXML\UIParent.lua:658>

**Comment by Industrial** [comment]
Hi @Havenloft, these are fixed with https://github.com/Industrial/idTweaks/releases/tag/v1.13.2-1.14.1, could you verify this?
