### ISSUE TITLE
Error on Classic:

### ISSUE THREAD

**Issue by Havenloft** [Industrial/idTweaks#4]
I disable all minimap options with IDT. I currently use EKMinimap_Classic as my minimap addon & these two addons are not currently compatible.
https://www.curseforge.com/wow/addons/ekminimap-classic

Error on Classic:

1x idTweaks\src\modules\Minimap.lua:283: Minimap:SetPoint(): MinimapCluster is dependent on this
[C]: in function `SetPoint'
idTweaks\src\modules\Minimap.lua:283: in function `disable'
idTweaks\src\modules\Minimap.lua:268: in function `check'
idTweaks\src\modules\Minimap.lua:228: in function <idTweaks\src\modules\Minimap.lua:222>
[C]: ?
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:540: in function `EnableAddon'
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:693: in function <FrameXML\UIParent.lua:658>

**Comment by Industrial** [comment]
Are you still experiencing this bug with the latest version, `v1.13.2-1.18.0` ?

**Comment by Industrial** [comment]
I'm closing this ticket since the whole Minimap module can now be turned off.
